import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');
const isSmallDevice = screenWidth < 375;
const visualScale = Math.min(screenWidth / 390, 1);

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  safeArea: {
    flex: 1,
    position: 'relative',
  },
  backgroundGlowTop: {
    position: 'absolute',
    top: -120,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: '#E2E8F0',
    opacity: 0.55,
  },
  backgroundGlowBottom: {
    position: 'absolute',
    bottom: -120,
    left: -90,
    width: 280,
    height: 280,
    borderRadius: 140,
    opacity: 0.7,
  },
  topBar: {
    paddingHorizontal: 24,
    paddingTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brand: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: 1.6,
  },
  brandSub: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
  },
  skipBtn: {
    height: 38,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'center',
  },
  skipText: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '700',
  },
  progressWrap: {
    paddingHorizontal: 24,
    paddingTop: 18,
    gap: 8,
  },
  progressTrackTop: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#E2E8F0',
    overflow: 'hidden',
  },
  progressFillTop: {
    height: '100%',
    borderRadius: 999,
  },
  progressLabel: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '700',
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 24,
  },
  heroWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 30,
  },
  visualStage: {
    width: '100%',
    maxWidth: 400,
    height: screenHeight * 0.38,
    maxHeight: 340,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  orb: {
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    opacity: 0.9,
  },
  visualCard: {
    padding: 14,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
    elevation: 4,
    gap: 8,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  visualSmall: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
  },
  visualValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
  },
  centerDevice: {
    width: Math.min(screenWidth * 0.65, 250),
    height: Math.min(screenHeight * 0.32, 270),
    borderRadius: 30,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    padding: 16,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 5,
  },
  deviceTop: {
    height: 58,
    borderRadius: 18,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  deviceDots: {
    flexDirection: 'row',
    gap: 6,
  },
  deviceDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#BFDBFE',
  },
  deviceContent: {
    flex: 1,
    gap: 12,
  },
  deviceGridRow: {
    flexDirection: 'row',
    gap: 10,
  },
  tileLarge: {
    flex: 1,
    height: 76,
    borderRadius: 18,
  },
  tileSmall: {
    flex: 1,
    height: 74,
    borderRadius: 16,
  },
  checkoutShell: {
    width: Math.min(screenWidth * 0.75, 280),
    padding: 18,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 5,
  },
  checkoutTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  checkoutTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
  },
  checkoutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  checkoutLine: {
    height: 14,
    borderRadius: 999,
    width: '68%',
  },
  checkoutPrice: {
    fontSize: 13,
    fontWeight: '700',
    color: '#334155',
  },
  progressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: '#EFF6FF',
    marginTop: 6,
    marginBottom: 18,
    overflow: 'hidden',
  },
  progressBar: {
    width: 86,
    height: '100%',
    borderRadius: 999,
  },
  payButtonMock: {
    height: 54,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  payButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 15,
  },
  successBadge: {
    position: 'absolute',
    right: 34,
    bottom: 34,
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 4,
  },
  analyticsPanel: {
    width: Math.min(screenWidth * 0.8, 300),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderRadius: 28,
    padding: 18,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 5,
  },
  analyticsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  analyticsEyebrow: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  analyticsHeadline: {
    marginTop: 3,
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
  },
  chartArea: {
    height: 132,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 12,
    marginBottom: 16,
  },
  chartBar: {
    flex: 1,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  statLabel: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '700',
  },
  statValue: {
    marginTop: 4,
    fontSize: 16,
    color: '#0F172A',
    fontWeight: '800',
  },
  readyCore: {
    width: 220,
    height: 220,
    borderRadius: 110,
    alignItems: 'center',
    justifyContent: 'center',
  },
  readyRing: {
    position: 'absolute',
    width: 184,
    height: 184,
    borderRadius: 92,
    borderWidth: 2,
    borderStyle: 'dashed',
  },
  readyCheck: {
    width: 84,
    height: 84,
    borderRadius: 42,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 4,
  },
  readyCardsWrap: {
    position: 'absolute',
    bottom: 12,
    flexDirection: 'row',
    gap: 12,
  },
  textWrap: {
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  eyebrowPill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    marginBottom: 16,
  },
  eyebrowText: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  title: {
    fontSize: isSmallDevice ? 28 : 36,
    lineHeight: isSmallDevice ? 34 : 42,
    fontWeight: '900',
    color: '#0F172A',
    textAlign: 'center',
    letterSpacing: -1,
    marginBottom: isSmallDevice ? 8 : 14,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 26,
    fontWeight: '500',
    color: '#475569',
    textAlign: 'center',
    maxWidth: 340,
  },
  footer: {
    paddingHorizontal: 24,
    paddingBottom: 18,
    gap: 16,
  },
  dotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#CBD5E1',
  },
  dotInactive: {
    backgroundColor: '#CBD5E1',
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    width: '100%',
    alignSelf: 'center',
  },
  navButton: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navButtonDisabled: {
    backgroundColor: '#F8FAFC',
  },
  ctaButton: {
    height: 58,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 6,
  },
  ctaText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  bottomCaption: {
    textAlign: 'center',
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: '700',
    letterSpacing: 0.4,
  },

});
